spring.application.name=TP2_Users
spring.datasource.url=jdbc:h2:mem:hospital
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8086
spring.h2.console.enabled=true
